- name: Download Java
  command: "wget -q -O {{ java_rpm_location }} --no-check-certificate --no-cookies --header 'Cookie:oraclelicense=accept-securebackup-cookie' {{java_download_url}} creates={{ java_rpm_location }}"

- name: Remove openJdk if exists
  yum: name={{ open_jdk_package }} state=absent

- name: install oracle java rpm
  yum: name={{ java_rpm_location }} state=present

- name: Make java available for system
  command: 'alternatives --install "/usr/bin/java" "java" "/usr/java/default/bin/java" 2000'


- name: Make javac available for system
  command: 'alternatives --install "/usr/bin/javac" "javac" "/usr/java/default/bin/javac" 2000'
  when: java_runtime == "jdk"


- name: Make jar available for system
  command: 'alternatives --install "/usr/bin/jar" "jar" "/usr/java/default/bin/jar" 2000'
  when: java_runtime == "jdk"

