- name: Download latest openmrs from bahmni-repo
  get_url: url=https://bahmni-repo.twhosted.com/packages/temp/openmrs-1.11.3.noarch.rpm dest=/tmp/openmrs-1.11.3.noarch.rpm mode=0755 force=no

- name: Install openmrs from bahmni-repo
  yum: name=/tmp/openmrs-1.11.3.noarch.rpm state=present

- name: Copy openmrs conf
  template:
    src=openmrs.conf.j2 
    dest={{ openmrs_install_dir }}/etc/openmrs.conf
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Copy openmrs-runtime properties
  template:
    src=openmrs-runtime.properties.j2
    dest={{ openmrs_install_dir }}/etc/openmrs-runtime.properties
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Openmrs db should be present
  mysql_db:
    name=openmrs
    state=present
    login_user=root
    login_password="{{ mysql_root_password }}"


- name: Get IpTable rules
  shell: iptables -L
  register: iptablesrules

- name: Allow bdshr port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport {{ openmrs_port }} -j ACCEPT -m comment --comment "OPENMRS"
  when: iptablesrules.stdout.find("OPENMRS") == -1

- name: save iptables
  command: service iptables save

- name: Start openmrs
  service: name=openmrs state=restarted enabled=yes
  tags: run_openmrs


