open_jdk_package: java-1.7.0-openjdk
download_folder: /opt
java_runtime: jre
java_rpm_name: "{{ java_runtime }}-7u75-linux-x64.rpm"
java_download_url: "http://download.oracle.com/otn-pub/java/jdk/7u75-b13/{{ java_rpm_name }}"
java_rpm_location: "{{download_folder}}/{{ java_rpm_name}}"